function seedFestivals(db) {
  const insert = db.prepare(`
    INSERT OR REPLACE INTO festivals (
      id, name, tier, location, month,
      submission_opens, early_deadline, regular_deadline, late_deadline,
      fee_early, fee_regular, fee_late,
      categories, genres, prestige, acceptance_rate,
      runtime_min, runtime_max, distribution_impact,
      notable_alumni, description, website, platform, notes, subject_tags,
      festival_start, festival_end
    ) VALUES (
      @id, @name, @tier, @location, @month,
      @submission_opens, @early_deadline, @regular_deadline, @late_deadline,
      @fee_early, @fee_regular, @fee_late,
      @categories, @genres, @prestige, @acceptance_rate,
      @runtime_min, @runtime_max, @distribution_impact,
      @notable_alumni, @description, @website, @platform, @notes, @subject_tags,
      @festival_start, @festival_end
    )
  `);

  const festivals = [
    // ── TIER 1 ────────────────────────────────────────────────────────
    {
      id: 'sundance', name: 'Sundance Film Festival', tier: 1,
      location: 'Park City, Utah, USA', month: 'January',
      submission_opens: 'August 1',
      early_deadline: 'September 15', regular_deadline: 'October 15', late_deadline: 'November 1',
      fee_early: 75, fee_regular: 95, fee_late: 120,
      festival_start: '2027-01-21', festival_end: '2027-01-31',
      categories: JSON.stringify(['US Dramatic', 'US Documentary', 'World Cinema Dramatic', 'World Cinema Documentary', 'NEXT', 'Shorts']),
      genres: JSON.stringify(['drama', 'documentary', 'comedy', 'thriller', 'experimental', 'animation']),
      prestige: 10, acceptance_rate: 0.003, runtime_min: 70, runtime_max: 130,
      distribution_impact: 'very high',
      notable_alumni: JSON.stringify(['Whiplash', 'Little Miss Sunshine', 'Napoleon Dynamite', 'Hereditary', 'Get Out', 'Fruitvale Station']),
      description: 'The premier American independent film festival. Launching ground for indie careers. World, international, or North American premieres required for competition.',
      website: 'https://sundance.org', platform: 'FilmFreeway',
      notes: 'Premieres matter — only world, international, or North American premieres accepted for competition. NEXT section for ultra-low-budget films under $1M.',
      subject_tags: JSON.stringify(['social justice', 'LGBTQ+', 'immigration', 'mental health', 'identity'])
    },
    {
      id: 'sxsw', name: 'SXSW Film & TV Festival', tier: 1,
      location: 'Austin, Texas, USA', month: 'March',
      submission_opens: 'August 15',
      early_deadline: 'September 20', regular_deadline: 'October 20', late_deadline: 'November 15',
      fee_early: 50, fee_regular: 75, fee_late: 100,
      festival_start: '2027-03-12', festival_end: '2027-03-21',
      categories: JSON.stringify(['Narrative Feature', 'Documentary Feature', 'Narrative Short', 'Documentary Short', 'Animated Short', 'Midnight', 'Episodic']),
      genres: JSON.stringify(['drama', 'comedy', 'documentary', 'horror', 'sci-fi', 'thriller', 'animation']),
      prestige: 9, acceptance_rate: 0.006, runtime_min: 60, runtime_max: 150,
      distribution_impact: 'very high',
      notable_alumni: JSON.stringify(['Get Out', 'Boyhood', 'Swiss Army Man', 'Safety Not Guaranteed', 'The Witch']),
      description: 'Austin festival combining film, music, and tech. Strong on genre films, comedy, and innovative storytelling. One of the best festivals for acquiring distribution.',
      website: 'https://sxsw.com/film', platform: 'FilmFreeway',
      notes: 'More genre-friendly than Sundance. Midnight section for horror/genre. Strong industry presence with buyers from all major streamers.',
      subject_tags: JSON.stringify(['technology', 'music', 'genre', 'comedy', 'innovation'])
    },
    {
      id: 'tribeca', name: 'Tribeca Film Festival', tier: 1,
      location: 'New York City, USA', month: 'June',
      submission_opens: 'October 1',
      early_deadline: 'November 15', regular_deadline: 'December 15', late_deadline: 'January 15',
      fee_early: 65, fee_regular: 85, fee_late: 110,
      festival_start: '2027-06-04', festival_end: '2027-06-15',
      categories: JSON.stringify(['US Narrative Feature', 'International Narrative Feature', 'Documentary Feature', 'Short Film', 'Immersive']),
      genres: JSON.stringify(['drama', 'documentary', 'comedy', 'thriller', 'experimental', 'animation']),
      prestige: 9, acceptance_rate: 0.005, runtime_min: 60, runtime_max: 150,
      distribution_impact: 'high',
      notable_alumni: JSON.stringify(['Beasts of the Southern Wild', 'Blue Ruin', 'The Invitation', 'Obvious Child']),
      description: 'New York-based festival founded post-9/11. Strong documentary program and narrative competition with major press presence.',
      website: 'https://tribecafilm.com', platform: 'FilmFreeway',
      notes: 'NYC location gives strong press access. Good for films with New York stories. Pairs well with a fall awards campaign.',
      subject_tags: JSON.stringify(['urban', 'social justice', 'journalism', 'documentary'])
    },
    {
      id: 'berlin', name: 'Berlinale (Berlin International Film Festival)', tier: 1,
      location: 'Berlin, Germany', month: 'February',
      submission_opens: 'September 1',
      early_deadline: 'October 15', regular_deadline: 'November 15', late_deadline: 'November 30',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-02-11', festival_end: '2027-02-21',
      categories: JSON.stringify(['Competition', 'Panorama', 'Forum', 'Generation', 'Berlinale Shorts', 'Encounters']),
      genres: JSON.stringify(['drama', 'documentary', 'experimental', 'animation', 'comedy']),
      prestige: 10, acceptance_rate: 0.002, runtime_min: 70, runtime_max: 180,
      distribution_impact: 'very high',
      notable_alumni: JSON.stringify(['Boyhood', 'The Hurt Locker', '12 Years a Slave', 'Capernaum', 'Touch Me Not']),
      description: "One of the three major European film festivals (with Cannes and Venice). The Golden Bear is one of cinema's most prestigious prizes. Free to submit.",
      website: 'https://berlinale.de', platform: 'Direct submission',
      notes: 'No submission fee. Politically engaged cinema preferred. Strong market (EFM) runs alongside. Panorama and Forum sections are more accessible for emerging filmmakers.',
      subject_tags: JSON.stringify(['political', 'social justice', 'immigration', 'LGBTQ+', 'human rights'])
    },
    {
      id: 'cannes', name: 'Festival de Cannes', tier: 1,
      location: 'Cannes, France', month: 'May',
      submission_opens: 'January 1',
      early_deadline: 'February 1', regular_deadline: 'March 1', late_deadline: 'March 15',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-05-13', festival_end: '2027-05-24',
      categories: JSON.stringify(["Palme d'Or Competition", 'Un Certain Regard', "Directors' Fortnight", "Critics' Week", "Short Film Palme d'Or"]),
      genres: JSON.stringify(['drama', 'documentary', 'experimental', 'thriller', 'animation']),
      prestige: 10, acceptance_rate: 0.001, runtime_min: 70, runtime_max: 200,
      distribution_impact: 'very high',
      notable_alumni: JSON.stringify(['Parasite', 'Pulp Fiction', 'Apocalypse Now', 'All About My Mother', 'Blue Is the Warmest Color']),
      description: "The world's most prestigious film festival. The Palme d'Or is the highest honor in cinema. Free to submit.",
      website: 'https://festival-cannes.com', platform: 'Direct submission',
      notes: "Extremely selective for Competition. Directors' Fortnight and Critics' Week are separate entities — sometimes more accessible for emerging filmmakers. Winning here is life-changing.",
      subject_tags: JSON.stringify(['arthouse', 'auteur', 'international', 'political'])
    },
    {
      id: 'venice', name: 'Venice Film Festival (La Biennale di Venezia)', tier: 1,
      location: 'Venice, Italy', month: 'August',
      submission_opens: 'March 1',
      early_deadline: 'April 15', regular_deadline: 'May 15', late_deadline: 'June 1',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-08-25', festival_end: '2027-09-04',
      categories: JSON.stringify(['Main Competition', 'Horizons (Orizzonti)', 'Venice Days', 'Orizzonti Extra', 'Shorts']),
      genres: JSON.stringify(['drama', 'documentary', 'experimental', 'thriller', 'animation']),
      prestige: 10, acceptance_rate: 0.002, runtime_min: 70, runtime_max: 200,
      distribution_impact: 'very high',
      notable_alumni: JSON.stringify(['Brokeback Mountain', 'Gravity', 'Joker', 'Nomadland', 'The Shape of Water', 'Roma']),
      description: "The world's oldest film festival. Traditionally a launching pad for Oscar-season films. Late August timing fits perfectly with awards campaigning.",
      website: 'https://labiennale.org/en/cinema', platform: 'Direct submission',
      notes: 'Strong track record for Oscar-winning films. Horizons section is more accessible than the main Competition. Free submission.',
      subject_tags: JSON.stringify(['arthouse', 'auteur', 'international', 'awards-oriented'])
    },
    {
      id: 'tiff', name: 'Toronto International Film Festival (TIFF)', tier: 1,
      location: 'Toronto, Canada', month: 'September',
      submission_opens: 'March 1',
      early_deadline: 'April 15', regular_deadline: 'May 15', late_deadline: 'June 1',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-09-09', festival_end: '2027-09-19',
      categories: JSON.stringify(['Special Presentations', 'Gala', 'Contemporary World Cinema', 'Discovery', 'Midnight Madness', 'Short Cuts']),
      genres: JSON.stringify(['drama', 'comedy', 'documentary', 'horror', 'thriller', 'animation', 'sci-fi']),
      prestige: 9, acceptance_rate: 0.004, runtime_min: 60, runtime_max: 200,
      distribution_impact: 'very high',
      notable_alumni: JSON.stringify(['Slumdog Millionaire', '12 Years a Slave', 'La La Land', 'Room', 'Spotlight', 'American Beauty']),
      description: 'The largest public film festival in the world. Critical launchpad for Oscar campaigns. The Audience Award (People\'s Choice) is a reliable Oscar predictor.',
      website: 'https://tiff.net', platform: 'Direct submission',
      notes: "No submission fee. Audience Award is a strong Oscar predictor. Midnight Madness for genre. September timing is perfect for awards season.",
      subject_tags: JSON.stringify(['commercial', 'awards-oriented', 'international', 'genre'])
    },
    {
      id: 'rotterdam', name: 'International Film Festival Rotterdam (IFFR)', tier: 1,
      location: 'Rotterdam, Netherlands', month: 'January',
      submission_opens: 'September 1',
      early_deadline: 'October 1', regular_deadline: 'November 1', late_deadline: 'November 15',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-01-28', festival_end: '2027-02-07',
      categories: JSON.stringify(['Tiger Competition', 'Bright Future', 'IFFR Pro', 'Shorts']),
      genres: JSON.stringify(['experimental', 'drama', 'documentary', 'animation']),
      prestige: 8, acceptance_rate: 0.005, runtime_min: 60, runtime_max: 200,
      distribution_impact: 'high',
      notable_alumni: JSON.stringify(['The Turin Horse', 'Uncle Boonmee', 'Tropical Malady', 'Cemetery of Splendour']),
      description: 'Adventurous festival championing bold, experimental, and innovative cinema. Tiger Award for debut and second films. Free submission.',
      website: 'https://iffr.com', platform: 'Direct submission',
      notes: 'Great for first and second features. Focuses on adventurous cinema. Has its own production fund (Hubert Bals Fund) for developing world filmmakers.',
      subject_tags: JSON.stringify(['experimental', 'arthouse', 'debut', 'innovative'])
    },
    {
      id: 'locarno', name: 'Locarno Film Festival', tier: 1,
      location: 'Locarno, Switzerland', month: 'August',
      submission_opens: 'March 1',
      early_deadline: 'April 1', regular_deadline: 'May 1', late_deadline: 'May 15',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-08-04', festival_end: '2027-08-14',
      categories: JSON.stringify(['International Competition', 'Piazza Grande', 'Filmmakers of the Present', 'Open Doors', 'Shorts']),
      genres: JSON.stringify(['drama', 'documentary', 'experimental', 'animation']),
      prestige: 8, acceptance_rate: 0.004, runtime_min: 60, runtime_max: 180,
      distribution_impact: 'high',
      notable_alumni: JSON.stringify(['My Own Private Idaho', 'Exotica', 'The Assassin', 'Storm']),
      description: 'Historic Swiss festival known for championing auteur cinema and first/second features. The Piazza Grande screens to thousands under the open sky.',
      website: 'https://locarnofestival.ch', platform: 'Direct submission',
      notes: 'Excellent for debut and second features. Open Doors focuses on underrepresented regions. Free submission.',
      subject_tags: JSON.stringify(['arthouse', 'auteur', 'debut', 'international'])
    },
    {
      id: 'idfa', name: 'IDFA — International Documentary Film Festival Amsterdam', tier: 1,
      location: 'Amsterdam, Netherlands', month: 'November',
      submission_opens: 'June 1',
      early_deadline: 'July 15', regular_deadline: 'August 31', late_deadline: 'September 15',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2026-11-19', festival_end: '2026-11-30',
      categories: JSON.stringify(['IDFA Competition', 'Envision Competition', 'First Appearance Competition', 'Masters', 'Shorts']),
      genres: JSON.stringify(['documentary']),
      prestige: 9, acceptance_rate: 0.007, runtime_min: 40, runtime_max: 180,
      distribution_impact: 'very high',
      notable_alumni: JSON.stringify(['Fahrenheit 9/11', 'Man on Wire', 'The Look of Silence', 'For Sama']),
      description: "The world's largest documentary festival. The Oscars of documentary filmmaking. Essential for any serious documentary film. Free to submit.",
      website: 'https://idfa.nl', platform: 'FilmFreeway',
      notes: 'Free to submit. World premiere preferred. Strong market (IDFA Forum). November timing supports Oscar campaigns.',
      subject_tags: JSON.stringify(['documentary', 'political', 'social justice', 'international', 'human rights'])
    },
    {
      id: 'sitges', name: 'Sitges International Fantastic Film Festival', tier: 1,
      location: 'Sitges, Spain', month: 'October',
      submission_opens: 'April 1',
      early_deadline: 'June 1', regular_deadline: 'July 15', late_deadline: 'August 15',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2026-10-08', festival_end: '2026-10-18',
      categories: JSON.stringify(['Official Fantastic Selection', 'Midnight X-treme', 'New Visions', "Anima't Animation"]),
      genres: JSON.stringify(['horror', 'sci-fi', 'fantasy', 'thriller', 'animation']),
      prestige: 9, acceptance_rate: 0.005, runtime_min: 70, runtime_max: 180,
      distribution_impact: 'very high',
      notable_alumni: JSON.stringify(["Pan's Labyrinth", 'The Others', 'Hereditary', 'Midsommar', 'A Tale of Two Sisters']),
      description: "The world's most prestigious genre film festival — the genre equivalent of Cannes. Winning here is massive for horror and sci-fi. Free to submit.",
      website: 'https://sitgesfilmfestival.com', platform: 'Direct submission',
      notes: 'The most prestigious genre festival worldwide. Free submission. European rights deals close here regularly.',
      subject_tags: JSON.stringify(['horror', 'sci-fi', 'fantasy', 'genre', 'European'])
    },
    {
      id: 'clermont-ferrand', name: 'Clermont-Ferrand International Short Film Festival', tier: 1,
      location: 'Clermont-Ferrand, France', month: 'February',
      submission_opens: 'June 1',
      early_deadline: 'September 1', regular_deadline: 'October 15', late_deadline: 'October 31',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-01-29', festival_end: '2027-02-06',
      categories: JSON.stringify(['International Competition', 'National Competition', 'Lab Competition', 'Panorama']),
      genres: JSON.stringify(['drama', 'documentary', 'animation', 'experimental', 'comedy']),
      prestige: 9, acceptance_rate: 0.005, runtime_min: 0, runtime_max: 40,
      distribution_impact: 'very high',
      notable_alumni: JSON.stringify(['Various Oscar-nominated shorts']),
      description: "The world's most important short film festival and market. Essential for short filmmakers. Has its own market for short film distribution. Free to submit.",
      website: 'https://clermont-filmfest.org', platform: 'Direct submission',
      notes: 'Short films ONLY (under 40 min). World premiere required for competition. Has a major market for short film rights.',
      subject_tags: JSON.stringify(['short film', 'international', 'animation', 'experimental'])
    },

    // ── TIER 2 ────────────────────────────────────────────────────────
    {
      id: 'afi', name: 'AFI Fest', tier: 2,
      location: 'Hollywood, California, USA', month: 'November',
      submission_opens: 'June 1',
      early_deadline: 'July 15', regular_deadline: 'August 15', late_deadline: 'September 30',
      fee_early: 45, fee_regular: 65, fee_late: 85,
      festival_start: '2026-10-22', festival_end: '2026-10-27',
      categories: JSON.stringify(['World Cinema', 'US Narrative', 'Documentary', 'Shorts', 'Special Screenings']),
      genres: JSON.stringify(['drama', 'documentary', 'comedy', 'thriller', 'animation']),
      prestige: 7, acceptance_rate: 0.01, runtime_min: 60, runtime_max: 180,
      distribution_impact: 'high',
      notable_alumni: JSON.stringify(['The Artist', 'Argo', 'Her', 'Moonlight', 'The Favourite']),
      description: 'Los Angeles-based festival organized by the American Film Institute. Strong industry attendance. Free screenings attract major buyers and press.',
      website: 'https://fest.afi.com', platform: 'FilmFreeway',
      notes: 'LA timing makes it ideal for Oscar campaigning. Screenings are free to the public, drawing large audiences and strong word of mouth.',
      subject_tags: JSON.stringify(['awards-oriented', 'commercial', 'international'])
    },
    {
      id: 'hotdocs', name: 'Hot Docs Canadian International Documentary Festival', tier: 2,
      location: 'Toronto, Canada', month: 'April',
      submission_opens: 'October 1',
      early_deadline: 'November 1', regular_deadline: 'December 1', late_deadline: 'January 15',
      fee_early: 45, fee_regular: 65, fee_late: 85,
      festival_start: '2027-04-29', festival_end: '2027-05-09',
      categories: JSON.stringify(['World Premiere', 'International Premiere', 'Canadian Premiere', 'Shorts']),
      genres: JSON.stringify(['documentary']),
      prestige: 8, acceptance_rate: 0.008, runtime_min: 40, runtime_max: 180,
      distribution_impact: 'high',
      notable_alumni: JSON.stringify(['Searching for Sugar Man', 'The Square', 'Virunga', 'All This Panic']),
      description: "North America's largest documentary festival and market. Essential for documentary filmmakers seeking distribution.",
      website: 'https://hotdocs.ca', platform: 'FilmFreeway',
      notes: 'Strong industry market (Hot Docs Forum, Deal Maker). Essential for doc distribution. Pitching forum for works-in-progress.',
      subject_tags: JSON.stringify(['documentary', 'journalism', 'social justice', 'environment'])
    },
    {
      id: 'truefalse', name: 'True/False Film Fest', tier: 2,
      location: 'Columbia, Missouri, USA', month: 'March',
      submission_opens: 'August 1',
      early_deadline: 'October 1', regular_deadline: 'November 15', late_deadline: 'December 31',
      fee_early: 40, fee_regular: 55, fee_late: 70,
      festival_start: '2027-02-25', festival_end: '2027-03-01',
      categories: JSON.stringify(['Documentary Feature', 'Short Documentary']),
      genres: JSON.stringify(['documentary']),
      prestige: 8, acceptance_rate: 0.01, runtime_min: 40, runtime_max: 180,
      distribution_impact: 'high',
      notable_alumni: JSON.stringify(['The Act of Killing', 'Searching for Sugar Man', "Stories We Tell", 'Caveat']),
      description: "Beloved documentary festival with a festive, community atmosphere. One of the most respected doc festivals in North America. Documentary-only.",
      website: 'https://truefalse.org', platform: 'FilmFreeway',
      notes: "Documentary-only. Extremely respected. 'Maysles Award' for direct cinema. Adventurous, humanistic selection.",
      subject_tags: JSON.stringify(['documentary', 'direct cinema', 'social justice', 'adventurous'])
    },
    {
      id: 'docnyc', name: 'DOC NYC', tier: 2,
      location: 'New York City, USA', month: 'November',
      submission_opens: 'May 1',
      early_deadline: 'June 15', regular_deadline: 'July 31', late_deadline: 'August 31',
      fee_early: 45, fee_regular: 60, fee_late: 80,
      festival_start: '2026-11-06', festival_end: '2026-11-15',
      categories: JSON.stringify(['Viewfinders', 'International Perspectives', 'American Perspectives', 'Short List', 'Shorts']),
      genres: JSON.stringify(['documentary']),
      prestige: 7, acceptance_rate: 0.012, runtime_min: 40, runtime_max: 180,
      distribution_impact: 'high',
      notable_alumni: JSON.stringify(['Three Identical Strangers', 'RBG', "Won't You Be My Neighbor", 'Allen v. Farrow']),
      description: "America's largest documentary festival. Essential for documentary distribution strategy. November NYC timing supports Oscar campaigns.",
      website: 'https://docnyc.net', platform: 'FilmFreeway',
      notes: "November timing is great for Oscar campaign. NYC industry attendance. Shortlist section highlights Oscar contenders.",
      subject_tags: JSON.stringify(['documentary', 'journalism', 'social justice', 'NYC'])
    },
    {
      id: 'fullframe', name: 'Full Frame Documentary Film Festival', tier: 2,
      location: 'Durham, North Carolina, USA', month: 'April',
      submission_opens: 'October 1',
      early_deadline: 'November 15', regular_deadline: 'December 31', late_deadline: 'January 15',
      fee_early: 40, fee_regular: 60, fee_late: 75,
      festival_start: '2027-04-03', festival_end: '2027-04-06',
      categories: JSON.stringify(['Feature Documentary', 'Short Documentary', 'Retrospective']),
      genres: JSON.stringify(['documentary']),
      prestige: 7, acceptance_rate: 0.01, runtime_min: 40, runtime_max: 180,
      distribution_impact: 'high',
      notable_alumni: JSON.stringify(['Citizenfour', 'The Act of Killing', "Stories We Tell", 'Hoop Dreams']),
      description: 'One of the premier documentary festivals in North America. Entirely focused on documentary cinema. Strong filmmaker community.',
      website: 'https://fullframefest.org', platform: 'FilmFreeway',
      notes: 'Documentary-only. Great for serious documentary work. Strong filmmaker community and critical discourse.',
      subject_tags: JSON.stringify(['documentary', 'journalism', 'social justice', 'human rights'])
    },
    {
      id: 'fantasia', name: 'Fantasia International Film Festival', tier: 2,
      location: 'Montreal, Canada', month: 'July',
      submission_opens: 'February 1',
      early_deadline: 'March 1', regular_deadline: 'April 15', late_deadline: 'May 15',
      fee_early: 30, fee_regular: 45, fee_late: 60,
      festival_start: '2027-07-15', festival_end: '2027-08-04',
      categories: JSON.stringify(['Cheval Noir (Horror/Genre)', 'Frontieres Co-production Market', 'Features', 'Shorts', 'Animation']),
      genres: JSON.stringify(['horror', 'sci-fi', 'thriller', 'animation', 'experimental', 'fantasy']),
      prestige: 7, acceptance_rate: 0.02, runtime_min: 40, runtime_max: 180,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['The Wailing', 'Under the Shadow', 'Turbo Kid', 'One Cut of the Dead', 'Tigers Are Not Afraid']),
      description: "North America's premier genre film festival. Essential for horror, sci-fi, thriller, and fantasy. Three weeks of programming.",
      website: 'https://fantasiafestival.com', platform: 'FilmFreeway',
      notes: "Best North American genre festival. Frontieres co-production market. Don't skip if you have a horror or genre film.",
      subject_tags: JSON.stringify(['horror', 'genre', 'sci-fi', 'fantasy', 'extreme'])
    },
    {
      id: 'frameline', name: 'Frameline Film Festival', tier: 2,
      location: 'San Francisco, California, USA', month: 'June',
      submission_opens: 'November 1',
      early_deadline: 'January 15', regular_deadline: 'February 28', late_deadline: 'March 31',
      fee_early: 35, fee_regular: 50, fee_late: 65,
      festival_start: '2027-06-17', festival_end: '2027-06-27',
      categories: JSON.stringify(['Feature Film', 'Documentary', 'Short Film', 'Centerpiece']),
      genres: JSON.stringify(['drama', 'documentary', 'comedy', 'experimental', 'animation']),
      prestige: 7, acceptance_rate: 0.02, runtime_min: 40, runtime_max: 180,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['Brokeback Mountain', 'The Kids Are All Right', 'Moonlight', 'Portrait of a Lady on Fire']),
      description: "The world's largest LGBTQ+ film festival. Essential for films with LGBTQ+ themes or perspectives.",
      website: 'https://frameline.org', platform: 'FilmFreeway',
      notes: 'Essential destination for LGBTQ+ cinema. Passionate and engaged audience. San Francisco Pride month timing.',
      subject_tags: JSON.stringify(['LGBTQ+', 'queer', 'identity', 'social justice'])
    },
    {
      id: 'outfest', name: 'Outfest Los Angeles LGBTQ+ Film Festival', tier: 2,
      location: 'Los Angeles, California, USA', month: 'July',
      submission_opens: 'January 1',
      early_deadline: 'February 15', regular_deadline: 'March 31', late_deadline: 'April 30',
      fee_early: 35, fee_regular: 50, fee_late: 65,
      festival_start: '2027-07-08', festival_end: '2027-07-18',
      categories: JSON.stringify(['Narrative Feature', 'Documentary Feature', 'Short Film', 'Episodic']),
      genres: JSON.stringify(['drama', 'comedy', 'documentary', 'thriller', 'animation']),
      prestige: 7, acceptance_rate: 0.02, runtime_min: 40, runtime_max: 180,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['Moonlight', 'Carol', 'Portrait of a Lady on Fire', 'Call Me By Your Name']),
      description: "The largest LGBTQ+ film festival on the West Coast. Strong LA industry connections and Outfest UCLA Legacy Project.",
      website: 'https://outfest.org', platform: 'FilmFreeway',
      notes: 'Essential for LGBTQ+ content. Strong industry connections in LA. Outfest UCLA Legacy Project preserves LGBTQ+ cinema.',
      subject_tags: JSON.stringify(['LGBTQ+', 'queer', 'identity', 'representation'])
    },
    {
      id: 'blackstar', name: 'BlackStar Film Festival', tier: 2,
      location: 'Philadelphia, Pennsylvania, USA', month: 'August',
      submission_opens: 'January 1',
      early_deadline: 'March 1', regular_deadline: 'April 15', late_deadline: 'May 31',
      fee_early: 30, fee_regular: 45, fee_late: 60,
      festival_start: '2027-07-29', festival_end: '2027-08-02',
      categories: JSON.stringify(['Narrative Feature', 'Documentary', 'Short Film', 'Experimental']),
      genres: JSON.stringify(['drama', 'documentary', 'comedy', 'experimental', 'animation']),
      prestige: 7, acceptance_rate: 0.02, runtime_min: 40, runtime_max: 180,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['Moonlight', 'Get Out', 'Beasts of the Southern Wild', 'Atlantics']),
      description: 'Celebrates films by and about people of the African diaspora and people of color globally.',
      website: 'https://blackstarfest.org', platform: 'FilmFreeway',
      notes: 'Essential for films by/about POC filmmakers. Strong community and critical engagement. Growing prestige.',
      subject_tags: JSON.stringify(['Black cinema', 'POC', 'diaspora', 'social justice', 'representation'])
    },
    {
      id: 'palmsprings', name: 'Palm Springs International Film Festival', tier: 2,
      location: 'Palm Springs, California, USA', month: 'January',
      submission_opens: 'August 1',
      early_deadline: 'September 1', regular_deadline: 'October 15', late_deadline: 'November 1',
      fee_early: 55, fee_regular: 70, fee_late: 90,
      festival_start: '2027-01-01', festival_end: '2027-01-12',
      categories: JSON.stringify(['New Voices/New Visions', 'World Cinema', 'Documentary', 'Shorts']),
      genres: JSON.stringify(['drama', 'comedy', 'documentary', 'thriller']),
      prestige: 7, acceptance_rate: 0.015, runtime_min: 60, runtime_max: 180,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['Amour', 'The Great Beauty', 'Ida', 'Son of Saul']),
      description: 'Major international film festival focused on world cinema. Known for its Foreign Language Film showcase supporting Oscar campaigns.',
      website: 'https://psfilmfest.org', platform: 'FilmFreeway',
      notes: 'Important for foreign language Oscar campaigns. Strong international focus. Awards gala draws major press.',
      subject_tags: JSON.stringify(['international', 'foreign language', 'awards-oriented'])
    },
    {
      id: 'sheffield', name: 'Sheffield Doc/Fest', tier: 2,
      location: 'Sheffield, United Kingdom', month: 'June',
      submission_opens: 'December 1',
      early_deadline: 'January 31', regular_deadline: 'February 28', late_deadline: 'March 31',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-06-11', festival_end: '2027-06-16',
      categories: JSON.stringify(['International Competition', 'UK Competition', 'Shorts Competition', 'Works in Progress']),
      genres: JSON.stringify(['documentary']),
      prestige: 8, acceptance_rate: 0.01, runtime_min: 40, runtime_max: 180,
      distribution_impact: 'high',
      notable_alumni: JSON.stringify(['Amy', 'Samsara', 'Grizzly Man', 'Searching for Sugar Man']),
      description: "The UK's most important documentary festival and market. The international doc community gathers here. Free to submit.",
      website: 'https://sheffdocfest.com', platform: 'FilmFreeway',
      notes: 'Documentary-only. Free to submit. Strong market component. BBC and Channel 4 attend. Good for UK/European broadcast deals.',
      subject_tags: JSON.stringify(['documentary', 'journalism', 'social justice', 'UK', 'BBC'])
    },
    {
      id: 'cphdox', name: 'CPH:DOX Copenhagen International Documentary Festival', tier: 2,
      location: 'Copenhagen, Denmark', month: 'March',
      submission_opens: 'October 1',
      early_deadline: 'November 15', regular_deadline: 'December 31', late_deadline: 'January 31',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-03-17', festival_end: '2027-03-28',
      categories: JSON.stringify(['CPH:DOX Award', 'Nordic:DOX', 'F:ACT Award', 'Next:Wave Award', 'Shorts']),
      genres: JSON.stringify(['documentary', 'experimental']),
      prestige: 8, acceptance_rate: 0.01, runtime_min: 40, runtime_max: 180,
      distribution_impact: 'high',
      notable_alumni: JSON.stringify(['The Mole', 'Armadillo', 'The Cremaster Cycle']),
      description: "One of Europe's largest documentary festivals. Adventurous programming mixing documentary with art and cross-disciplinary work. Free to submit.",
      website: 'https://cphdox.dk', platform: 'FilmFreeway',
      notes: 'Free to submit. Nordic focus but international scope. Cross-disciplinary art+doc approach. Strong for adventurous, hybrid work.',
      subject_tags: JSON.stringify(['documentary', 'Nordic', 'art', 'experimental', 'European'])
    },
    {
      id: 'bamcinema', name: 'BAMcinemaFest', tier: 2,
      location: 'Brooklyn, New York, USA', month: 'June',
      submission_opens: 'January 1',
      early_deadline: 'February 15', regular_deadline: 'March 31', late_deadline: 'April 30',
      fee_early: 40, fee_regular: 55, fee_late: 70,
      festival_start: '2027-06-10', festival_end: '2027-06-20',
      categories: JSON.stringify(['Feature Film', 'Documentary', 'Short Film']),
      genres: JSON.stringify(['drama', 'comedy', 'documentary', 'experimental']),
      prestige: 6, acceptance_rate: 0.025, runtime_min: 50, runtime_max: 150,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['Tangerine', 'Obvious Child', 'Listen Up Philip', 'Mediterranea']),
      description: 'Brooklyn-based festival championing emerging American independent filmmakers. Strong critical and press community.',
      website: 'https://bam.org/cinemafest', platform: 'FilmFreeway',
      notes: 'Great for emerging US indie directors. Strong New York critical community. Good press access.',
      subject_tags: JSON.stringify(['indie', 'emerging', 'US independent', 'urban'])
    },
    {
      id: 'siff', name: 'Seattle International Film Festival (SIFF)', tier: 2,
      location: 'Seattle, Washington, USA', month: 'May',
      submission_opens: 'November 1',
      early_deadline: 'January 15', regular_deadline: 'February 28', late_deadline: 'March 31',
      fee_early: 45, fee_regular: 65, fee_late: 85,
      festival_start: '2027-05-13', festival_end: '2027-06-06',
      categories: JSON.stringify(['American Independents', 'World Cinema', 'Documentary', 'Shorts', 'LGBTQ+']),
      genres: JSON.stringify(['drama', 'comedy', 'documentary', 'thriller', 'animation', 'horror']),
      prestige: 7, acceptance_rate: 0.015, runtime_min: 40, runtime_max: 180,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['Green Room', 'The Witch', 'Columbus', 'Hunt for the Wilderpeople']),
      description: "One of the largest film festivals in North America. Audience-driven with strong community support. Cash prizes available.",
      website: 'https://siff.net', platform: 'FilmFreeway',
      notes: 'Large audience-focused festival. Strong in Pacific Northwest. Three weeks of screenings across multiple venues.',
      subject_tags: JSON.stringify(['indie', 'community', 'Pacific Northwest', 'audience-driven'])
    },
    {
      id: 'newfest', name: 'NewFest: New York LGBTQ+ Film Festival', tier: 2,
      location: 'New York City, USA', month: 'October',
      submission_opens: 'May 1',
      early_deadline: 'June 15', regular_deadline: 'July 31', late_deadline: 'August 31',
      fee_early: 30, fee_regular: 45, fee_late: 60,
      festival_start: '2026-10-14', festival_end: '2026-10-24',
      categories: JSON.stringify(['Feature Film', 'Documentary', 'Short Film']),
      genres: JSON.stringify(['drama', 'comedy', 'documentary', 'thriller', 'animation']),
      prestige: 6, acceptance_rate: 0.03, runtime_min: 40, runtime_max: 180,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['Brokeback Mountain', 'Carol', 'Portrait of a Lady on Fire']),
      description: "New York's premier LGBTQ+ film festival with strong industry and community presence. October timing pre-awards.",
      website: 'https://newfest.org', platform: 'FilmFreeway',
      notes: 'Essential for LGBTQ+ films in NYC. Strong critical community. October timing is good for fall awards.',
      subject_tags: JSON.stringify(['LGBTQ+', 'queer', 'NYC', 'identity'])
    },
    {
      id: 'bifan', name: 'Bucheon International Fantastic Film Festival (BIFAN)', tier: 2,
      location: 'Bucheon, South Korea', month: 'July',
      submission_opens: 'January 1',
      early_deadline: 'March 1', regular_deadline: 'March 31', late_deadline: 'April 15',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-07-08', festival_end: '2027-07-18',
      categories: JSON.stringify(['Official Competition', 'Korean Fantastic', 'Bucheon Choice', 'Shorts']),
      genres: JSON.stringify(['horror', 'sci-fi', 'thriller', 'fantasy', 'animation']),
      prestige: 7, acceptance_rate: 0.02, runtime_min: 40, runtime_max: 180,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['Train to Busan', 'A Tale of Two Sisters', 'I Saw the Devil']),
      description: "Asia's premier genre film festival. Essential for Asian market genre exposure. Free submission.",
      website: 'https://bifan.kr', platform: 'FilmFreeway',
      notes: 'Free submission. Key gateway to Asian distribution market. Strong genre programming.',
      subject_tags: JSON.stringify(['horror', 'genre', 'Asian market', 'international', 'sci-fi'])
    },
    {
      id: 'frightfest', name: 'Arrow Video FrightFest', tier: 2,
      location: 'London, United Kingdom', month: 'August',
      submission_opens: 'February 1',
      early_deadline: 'April 1', regular_deadline: 'May 15', late_deadline: 'June 15',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-08-26', festival_end: '2027-08-30',
      categories: JSON.stringify(['Main Screen', 'Discovery Screen', 'Shorts']),
      genres: JSON.stringify(['horror', 'thriller', 'sci-fi', 'fantasy']),
      prestige: 7, acceptance_rate: 0.02, runtime_min: 40, runtime_max: 150,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['The Descent', 'Eden Lake', 'Pontypool', 'The Autopsy of Jane Doe']),
      description: "The UK's premier horror film festival. Bank holiday weekend celebration in London. Free to submit.",
      website: 'https://frightfest.co.uk', platform: 'FilmFreeway',
      notes: 'Free submission. Passionate horror audience. Good for UK/European distribution attention.',
      subject_tags: JSON.stringify(['horror', 'thriller', 'UK', 'genre'])
    },
    {
      id: 'bafici', name: 'Buenos Aires International Independent Film Festival (BAFICI)', tier: 2,
      location: 'Buenos Aires, Argentina', month: 'April',
      submission_opens: 'October 1',
      early_deadline: 'December 1', regular_deadline: 'January 15', late_deadline: 'January 31',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-04-14', festival_end: '2027-04-24',
      categories: JSON.stringify(['International Competition', 'Argentine Competition', 'Panorama', 'Shorts']),
      genres: JSON.stringify(['drama', 'documentary', 'experimental', 'animation', 'comedy']),
      prestige: 7, acceptance_rate: 0.015, runtime_min: 50, runtime_max: 180,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify([]),
      description: "Latin America's most important independent film festival. Free submission.",
      website: 'https://bafici.gob.ar', platform: 'Direct submission',
      notes: 'Free submission. Key for Latin American market exposure. Strong art cinema focus.',
      subject_tags: JSON.stringify(['Latin America', 'independent', 'arthouse', 'international'])
    },

    // ── TIER 3 ────────────────────────────────────────────────────────
    {
      id: 'slamdance', name: 'Slamdance Film Festival', tier: 3,
      location: 'Park City, Utah, USA', month: 'January',
      submission_opens: 'August 1',
      early_deadline: 'September 15', regular_deadline: 'October 15', late_deadline: 'November 1',
      fee_early: 35, fee_regular: 50, fee_late: 65,
      festival_start: '2027-01-21', festival_end: '2027-01-27',
      categories: JSON.stringify(['Feature Film', 'Documentary', 'Short Film', 'Anarchy']),
      genres: JSON.stringify(['drama', 'comedy', 'documentary', 'horror', 'experimental']),
      prestige: 5, acceptance_rate: 0.04, runtime_min: 40, runtime_max: 150,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['Saw', 'Paranormal Activity', 'Whiplash (premiered here before Sundance)']),
      description: 'The anti-Sundance festival running simultaneously in Park City. Champion of truly independent, micro-budget filmmaking.',
      website: 'https://slamdance.com', platform: 'FilmFreeway',
      notes: 'Runs same time/location as Sundance. Good industry presence. Budget cap usually applies. True indie spirit.',
      subject_tags: JSON.stringify(['micro-budget', 'ultra-indie', 'experimental', 'debut'])
    },
    {
      id: 'overlook', name: 'Overlook Film Festival', tier: 3,
      location: 'New Orleans, Louisiana, USA', month: 'May',
      submission_opens: 'November 1',
      early_deadline: 'January 15', regular_deadline: 'February 15', late_deadline: 'March 15',
      fee_early: 40, fee_regular: 55, fee_late: 70,
      festival_start: '2027-04-29', festival_end: '2027-05-03',
      categories: JSON.stringify(['Feature Film', 'Short Film', 'Virtual Reality']),
      genres: JSON.stringify(['horror', 'thriller', 'sci-fi', 'experimental', 'fantasy']),
      prestige: 6, acceptance_rate: 0.03, runtime_min: 40, runtime_max: 150,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['The Night Eats the World', 'Haunt', 'Slaxx', 'The Sadness']),
      description: "Premier American horror and genre festival. Named after The Shining's Overlook Hotel. New Orleans atmosphere adds to the experience.",
      website: 'https://overlookfilmfest.com', platform: 'FilmFreeway',
      notes: 'Best US horror festival after Fantasia. New Orleans atmosphere adds to the experience.',
      subject_tags: JSON.stringify(['horror', 'genre', 'thriller', 'supernatural'])
    },
    {
      id: 'nashville', name: 'Nashville Film Festival', tier: 3,
      location: 'Nashville, Tennessee, USA', month: 'April',
      submission_opens: 'October 1',
      early_deadline: 'December 1', regular_deadline: 'January 15', late_deadline: 'February 15',
      fee_early: 35, fee_regular: 50, fee_late: 65,
      festival_start: '2027-04-03', festival_end: '2027-04-12',
      categories: JSON.stringify(['Narrative Feature', 'Documentary', 'Short Film', 'Music Video']),
      genres: JSON.stringify(['drama', 'comedy', 'documentary', 'thriller', 'music']),
      prestige: 5, acceptance_rate: 0.04, runtime_min: 50, runtime_max: 150,
      distribution_impact: 'low',
      notable_alumni: JSON.stringify(["The Color Purple", "Coal Miner's Daughter"]),
      description: 'One of the oldest film festivals in the US. Strong focus on music and Southern storytelling.',
      website: 'https://nashvillefilmfestival.org', platform: 'FilmFreeway',
      notes: 'Great for music-themed films and Southern stories. Accessible for emerging filmmakers.',
      subject_tags: JSON.stringify(['music', 'southern', 'americana', 'indie'])
    },
    {
      id: 'tallgrass', name: 'Tallgrass Film Festival', tier: 3,
      location: 'Wichita, Kansas, USA', month: 'October',
      submission_opens: 'April 1',
      early_deadline: 'June 1', regular_deadline: 'July 15', late_deadline: 'August 15',
      fee_early: 25, fee_regular: 40, fee_late: 55,
      festival_start: '2026-10-07', festival_end: '2026-10-11',
      categories: JSON.stringify(['Narrative Feature', 'Documentary', 'Short Film', 'Animated Short']),
      genres: JSON.stringify(['drama', 'comedy', 'documentary', 'thriller', 'animation']),
      prestige: 4, acceptance_rate: 0.05, runtime_min: 40, runtime_max: 150,
      distribution_impact: 'low',
      notable_alumni: JSON.stringify(["Winter's Bone", 'Beasts of the Southern Wild']),
      description: 'Accessible Midwest festival with a welcoming community for emerging filmmakers.',
      website: 'https://tallgrassfilm.org', platform: 'FilmFreeway',
      notes: 'Great stepping stone for emerging filmmakers. Strong community atmosphere.',
      subject_tags: JSON.stringify(['indie', 'emerging', 'midwest', 'community'])
    },
    {
      id: 'danceswithfilms', name: 'Dances With Films', tier: 3,
      location: 'Hollywood, California, USA', month: 'June',
      submission_opens: 'November 1',
      early_deadline: 'January 15', regular_deadline: 'February 28', late_deadline: 'March 31',
      fee_early: 30, fee_regular: 45, fee_late: 60,
      festival_start: '2027-06-05', festival_end: '2027-06-15',
      categories: JSON.stringify(['Narrative Feature', 'Documentary', 'Short Film', 'Web Series']),
      genres: JSON.stringify(['drama', 'comedy', 'thriller', 'documentary', 'animation']),
      prestige: 4, acceptance_rate: 0.06, runtime_min: 40, runtime_max: 150,
      distribution_impact: 'low',
      notable_alumni: JSON.stringify(['The Big Sick', "Before the Devil Knows You're Dead"]),
      description: 'Hollywood-based festival showcasing undiscovered talent. No stars, no strings, no bull.',
      website: 'https://danceswithfilms.com', platform: 'FilmFreeway',
      notes: 'Good for networking in LA. Industry accessible. Strong for emerging filmmakers.',
      subject_tags: JSON.stringify(['emerging', 'indie', 'debut', 'LA industry'])
    },
    {
      id: 'woodshole', name: 'Woods Hole Film Festival', tier: 3,
      location: 'Woods Hole, Massachusetts, USA', month: 'July',
      submission_opens: 'January 1',
      early_deadline: 'March 1', regular_deadline: 'April 1', late_deadline: 'May 1',
      fee_early: 25, fee_regular: 35, fee_late: 45,
      festival_start: '2027-07-26', festival_end: '2027-08-01',
      categories: JSON.stringify(['Feature Film', 'Documentary', 'Short Film', 'Animation']),
      genres: JSON.stringify(['drama', 'documentary', 'animation', 'experimental']),
      prestige: 4, acceptance_rate: 0.06, runtime_min: 40, runtime_max: 150,
      distribution_impact: 'low',
      notable_alumni: JSON.stringify(['First Reformed', 'Beasts of the Southern Wild']),
      description: 'Charming seaside festival in Cape Cod. Community-focused with a curated selection.',
      website: 'https://woodsholefilmfestival.org', platform: 'FilmFreeway',
      notes: 'Great community atmosphere. Good for quiet, contemplative films.',
      subject_tags: JSON.stringify(['community', 'contemplative', 'indie', 'New England'])
    },
    {
      id: 'annarbor', name: 'Ann Arbor Film Festival', tier: 3,
      location: 'Ann Arbor, Michigan, USA', month: 'March',
      submission_opens: 'October 1',
      early_deadline: 'November 15', regular_deadline: 'December 31', late_deadline: 'January 31',
      fee_early: 25, fee_regular: 35, fee_late: 50,
      festival_start: '2027-03-16', festival_end: '2027-03-21',
      categories: JSON.stringify(['Experimental', 'Animation', 'Documentary', 'Narrative']),
      genres: JSON.stringify(['experimental', 'animation', 'documentary', 'drama']),
      prestige: 5, acceptance_rate: 0.05, runtime_min: 0, runtime_max: 60,
      distribution_impact: 'low',
      notable_alumni: JSON.stringify([]),
      description: 'One of the oldest independent film festivals in the US. Focus on experimental and avant-garde cinema.',
      website: 'https://aafilmfest.org', platform: 'FilmFreeway',
      notes: 'Great for experimental and avant-garde work. University town audience.',
      subject_tags: JSON.stringify(['experimental', 'avant-garde', 'animation', 'academic'])
    },
    {
      id: 'popcornfrights', name: 'Popcorn Frights Film Festival', tier: 3,
      location: 'Fort Lauderdale, Florida, USA', month: 'August',
      submission_opens: 'January 1',
      early_deadline: 'March 1', regular_deadline: 'April 15', late_deadline: 'May 31',
      fee_early: 25, fee_regular: 40, fee_late: 55,
      festival_start: '2027-08-12', festival_end: '2027-08-22',
      categories: JSON.stringify(['Feature Film', 'Short Film']),
      genres: JSON.stringify(['horror', 'thriller', 'sci-fi', 'fantasy']),
      prestige: 4, acceptance_rate: 0.06, runtime_min: 40, runtime_max: 150,
      distribution_impact: 'low',
      notable_alumni: JSON.stringify([]),
      description: "Florida's largest genre film festival. Growing reputation in horror community.",
      website: 'https://popcornfrights.com', platform: 'FilmFreeway',
      notes: 'Good regional horror festival. Passionate genre audience. Growing prestige.',
      subject_tags: JSON.stringify(['horror', 'genre', 'regional', 'Florida'])
    },
    {
      id: 'deadbydawn', name: 'Dead by Dawn Scottish Horror Festival', tier: 3,
      location: 'Edinburgh, Scotland, UK', month: 'April',
      submission_opens: 'November 1',
      early_deadline: 'January 15', regular_deadline: 'February 28', late_deadline: 'March 15',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-04-23', festival_end: '2027-04-26',
      categories: JSON.stringify(['Feature Film', 'Short Film']),
      genres: JSON.stringify(['horror', 'thriller', 'sci-fi', 'fantasy']),
      prestige: 5, acceptance_rate: 0.05, runtime_min: 40, runtime_max: 150,
      distribution_impact: 'low',
      notable_alumni: JSON.stringify([]),
      description: "Scotland's premier horror film festival. Cult following in the UK horror community. Free to submit.",
      website: 'https://deadbydawn.co.uk', platform: 'FilmFreeway',
      notes: 'Free submission. Good for UK horror networking. Cult horror audience.',
      subject_tags: JSON.stringify(['horror', 'UK', 'cult', 'Scottish'])
    },
    {
      id: 'fantaspoa', name: 'Fantaspoa International Fantastic Film Festival', tier: 3,
      location: 'Porto Alegre, Brazil', month: 'April',
      submission_opens: 'November 1',
      early_deadline: 'January 1', regular_deadline: 'February 15', late_deadline: 'February 28',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-04-23', festival_end: '2027-05-03',
      categories: JSON.stringify(['Feature Film', 'Short Film', 'Brazilian Competition']),
      genres: JSON.stringify(['horror', 'sci-fi', 'thriller', 'fantasy', 'animation']),
      prestige: 5, acceptance_rate: 0.04, runtime_min: 40, runtime_max: 180,
      distribution_impact: 'low',
      notable_alumni: JSON.stringify([]),
      description: "Latin America's most important genre film festival. Free submission.",
      website: 'https://fantaspoa.com', platform: 'FilmFreeway',
      notes: 'Free to submit. Great for international exposure in Latin America. Horror/genre focus.',
      subject_tags: JSON.stringify(['horror', 'genre', 'Latin America', 'international'])
    },
    {
      id: 'sundanceshorts', name: 'Sundance Short Film Competition', tier: 1,
      location: 'Park City, Utah, USA', month: 'January',
      submission_opens: 'August 1',
      early_deadline: 'September 15', regular_deadline: 'October 15', late_deadline: 'November 1',
      fee_early: 50, fee_regular: 70, fee_late: 90,
      festival_start: '2027-01-21', festival_end: '2027-01-31',
      categories: JSON.stringify(['Short Film Competition', 'Animated Short', 'Documentary Short']),
      genres: JSON.stringify(['drama', 'documentary', 'animation', 'experimental', 'comedy']),
      prestige: 10, acceptance_rate: 0.004, runtime_min: 0, runtime_max: 40,
      distribution_impact: 'very high',
      notable_alumni: JSON.stringify(['Stutterer (Oscar winner)', 'The Gunfighter', 'Curfew (Oscar winner)', 'Whiplash (original short)']),
      description: 'The most prestigious short film competition in North America. Oscar qualifying. Career-launching for short filmmakers.',
      website: 'https://sundance.org', platform: 'FilmFreeway',
      notes: 'Short films only (under 40 min). Oscar qualifying. Often leads directly to feature film opportunities.',
      subject_tags: JSON.stringify(['short film', 'Oscar qualifier', 'career-launching'])
    },

    // ── TIER 1 (additional) ───────────────────────────────────────────
    {
      id: 'telluride', name: 'Telluride Film Festival', tier: 1,
      location: 'Telluride, Colorado, USA', month: 'September',
      submission_opens: 'May 1',
      early_deadline: 'June 1', regular_deadline: 'July 1', late_deadline: 'July 15',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-08-27', festival_end: '2027-08-31',
      categories: JSON.stringify(['Main Slate', 'New Directors', 'Shorts']),
      genres: JSON.stringify(['drama', 'documentary', 'experimental', 'animation']),
      prestige: 10, acceptance_rate: 0.001, runtime_min: 70, runtime_max: 180,
      distribution_impact: 'very high',
      notable_alumni: JSON.stringify(["The King's Speech", 'Spotlight', 'Arrival', 'Brokeback Mountain', 'Manchester by the Sea', 'Nomadland']),
      description: 'Exclusive mountain festival known for world premieres of Oscar contenders. Invitation-only, no open submissions — but films screened here consistently win awards.',
      website: 'https://telluridefilmfestival.org', platform: 'Direct invitation',
      notes: 'Invitation-only — no public submission. Best path in is through a sales agent or established distributor. Premiering here is a near-guarantee of awards season buzz.',
      subject_tags: JSON.stringify(['prestige', 'awards season', 'drama', 'Oscar contender'])
    },
    {
      id: 'nyff', name: 'New York Film Festival (NYFF)', tier: 1,
      location: 'New York City, USA', month: 'October',
      submission_opens: 'April 1',
      early_deadline: 'May 15', regular_deadline: 'June 15', late_deadline: 'July 1',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-09-26', festival_end: '2027-10-12',
      categories: JSON.stringify(['Main Slate', 'Spotlight on Documentary', 'Projections', 'Revivals', 'Short Films']),
      genres: JSON.stringify(['drama', 'documentary', 'experimental', 'animation']),
      prestige: 10, acceptance_rate: 0.002, runtime_min: 60, runtime_max: 200,
      distribution_impact: 'very high',
      notable_alumni: JSON.stringify(['Boyhood', 'The Social Network', 'Carol', 'Marriage Story', 'Portrait of a Lady on Fire']),
      description: 'Prestigious curated festival organized by Film at Lincoln Center. Main slate selections are hand-picked by the selection committee. Strong critical establishment and press profile.',
      website: 'https://filmlinc.org/nyff', platform: 'Direct submission',
      notes: 'Main slate is highly curated. Projections section is more accessible for experimental work. Strong for critical reputation and NYC press coverage.',
      subject_tags: JSON.stringify(['prestige', 'critical darling', 'New York', 'international cinema'])
    },
    {
      id: 'bfi-london', name: 'BFI London Film Festival', tier: 1,
      location: 'London, UK', month: 'October',
      submission_opens: 'April 15',
      early_deadline: 'June 1', regular_deadline: 'July 1', late_deadline: 'July 15',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-10-08', festival_end: '2027-10-19',
      categories: JSON.stringify(['Official Competition', 'Documentary Competition', 'Short Film Competition', 'First Feature Competition', 'Cult']),
      genres: JSON.stringify(['drama', 'documentary', 'experimental', 'animation', 'comedy', 'thriller']),
      prestige: 9, acceptance_rate: 0.004, runtime_min: 60, runtime_max: 200,
      distribution_impact: 'very high',
      notable_alumni: JSON.stringify(['Moonlight', 'The Favourite', 'Roma', 'I, Daniel Blake', "Lady Bird"]),
      description: "The UK's most prestigious film festival. Strong European and international cinema program. Excellent for British and British co-production films.",
      website: 'https://bfi.org.uk/london-film-festival', platform: 'FilmFreeway',
      notes: 'Free to submit. Excellent for films seeking UK distribution. Strong BBC Films and Film4 industry presence. First Feature competition is a great entry point.',
      subject_tags: JSON.stringify(['British cinema', 'European cinema', 'prestige', 'awards season'])
    },
    {
      id: 'san-sebastian', name: 'San Sebastián International Film Festival', tier: 1,
      location: 'San Sebastián, Spain', month: 'September',
      submission_opens: 'May 1',
      early_deadline: 'June 15', regular_deadline: 'July 15', late_deadline: 'August 1',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-09-17', festival_end: '2027-09-25',
      categories: JSON.stringify(['Official Selection', 'New Directors', 'Horizontes Latinos', 'Made in Spain', 'Zabaltegi-Tabakalera', 'Velodrome']),
      genres: JSON.stringify(['drama', 'comedy', 'documentary', 'thriller', 'experimental']),
      prestige: 9, acceptance_rate: 0.005, runtime_min: 60, runtime_max: 180,
      distribution_impact: 'high',
      notable_alumni: JSON.stringify(['The Clan', 'Gloria', 'The Headless Woman', 'Toni Erdmann']),
      description: "One of Europe's oldest and most respected festivals. Strong Latin American program. Horizontes Latinos section is ideal for Latin American films.",
      website: 'https://sansebastianfestival.com', platform: 'FilmFreeway',
      notes: 'Free to submit. Best European entry point for Latin American films. New Directors section is highly competitive but excellent for debuts.',
      subject_tags: JSON.stringify(['Spanish cinema', 'Latin America', 'European', 'debut feature'])
    },
    {
      id: 'karlovy-vary', name: 'Karlovy Vary International Film Festival', tier: 1,
      location: 'Karlovy Vary, Czech Republic', month: 'July',
      submission_opens: 'February 1',
      early_deadline: 'March 15', regular_deadline: 'April 15', late_deadline: 'May 1',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-07-02', festival_end: '2027-07-10',
      categories: JSON.stringify(['Main Competition', 'Proxima', 'Documentary', 'East of the West', 'Horizons']),
      genres: JSON.stringify(['drama', 'documentary', 'comedy', 'experimental']),
      prestige: 8, acceptance_rate: 0.006, runtime_min: 60, runtime_max: 180,
      distribution_impact: 'high',
      notable_alumni: JSON.stringify(['Amelie', 'Kolya', 'Divided We Fall', 'My Joy']),
      description: 'Major Central/Eastern European festival. Free to submit. Strong focus on Central European and world cinema. East of the West section highlights films from the region.',
      website: 'https://kviff.com', platform: 'FilmFreeway',
      notes: 'Free to submit. Best gateway for Central/Eastern European films to wider audience. Strong industry market.',
      subject_tags: JSON.stringify(['Central European', 'Eastern European', 'world cinema', 'international'])
    },

    // ── TIER 2 (additional) ───────────────────────────────────────────
    {
      id: 'sfiff', name: 'San Francisco International Film Festival (SFIFF)', tier: 2,
      location: 'San Francisco, California, USA', month: 'April',
      submission_opens: 'October 1',
      early_deadline: 'November 15', regular_deadline: 'December 15', late_deadline: 'January 15',
      fee_early: 45, fee_regular: 65, fee_late: 85,
      festival_start: '2027-04-16', festival_end: '2027-04-30',
      categories: JSON.stringify(['Golden Gate Award', 'Documentary', 'Short Film', 'New Directors']),
      genres: JSON.stringify(['drama', 'documentary', 'experimental', 'animation', 'comedy', 'sci-fi']),
      prestige: 7, acceptance_rate: 0.02, runtime_min: 0, runtime_max: 200,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['Searching for Sugar Man', 'The Act of Killing', 'Tangerine']),
      description: "America's longest-running international film festival. Strong Bay Area tech-culture crossover and diverse programming.",
      website: 'https://sffilm.org', platform: 'FilmFreeway',
      notes: 'Strong documentary program. Good West Coast industry contacts and tech-adjacent audience. Golden Gate Award carries real weight.',
      subject_tags: JSON.stringify(['documentary', 'technology', 'Bay Area', 'international', 'experimental'])
    },
    {
      id: 'austin-ff', name: 'Austin Film Festival', tier: 2,
      location: 'Austin, Texas, USA', month: 'October',
      submission_opens: 'March 1',
      early_deadline: 'May 15', regular_deadline: 'June 15', late_deadline: 'July 15',
      fee_early: 40, fee_regular: 55, fee_late: 70,
      festival_start: '2027-10-21', festival_end: '2027-10-28',
      categories: JSON.stringify(['Feature Film Competition', 'Short Film', 'Documentary', 'Screenplay Competition']),
      genres: JSON.stringify(['drama', 'comedy', 'documentary', 'thriller', 'short']),
      prestige: 6, acceptance_rate: 0.05, runtime_min: 0, runtime_max: 180,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['Slacker', 'The Watcher', 'Bernie']),
      description: "Combines film festival with one of the world's premier screenplay conferences. Strong for writer-directors. Focus on story-driven cinema.",
      website: 'https://austinfilmfestival.com', platform: 'FilmFreeway',
      notes: 'Excellent for writer-directors. Unique screenplay competition alongside film screenings. Strong networking with established screenwriters.',
      subject_tags: JSON.stringify(['screenplay', 'writer-director', 'story-driven', 'Texas'])
    },
    {
      id: 'sarajevo', name: 'Sarajevo Film Festival', tier: 2,
      location: 'Sarajevo, Bosnia and Herzegovina', month: 'August',
      submission_opens: 'March 1',
      early_deadline: 'April 15', regular_deadline: 'May 15', late_deadline: 'June 1',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-08-13', festival_end: '2027-08-21',
      categories: JSON.stringify(['Competition', 'Documentary Competition', 'Short Film Competition', 'Open Air']),
      genres: JSON.stringify(['drama', 'documentary', 'experimental', 'comedy']),
      prestige: 7, acceptance_rate: 0.02, runtime_min: 60, runtime_max: 180,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(["No Man's Land", 'An Episode in the Life of an Iron Picker', 'Death in Sarajevo']),
      description: "The most important film festival in Southeast Europe. Free to submit. Strong focus on Balkan and European cinema. Unique open-air screenings.",
      website: 'https://sff.ba', platform: 'Direct submission',
      notes: 'Free to submit. Best gateway for Balkan and Southeast European films. Open-air screening is culturally unique. Strong regional industry.',
      subject_tags: JSON.stringify(['Balkan', 'Eastern European', 'war', 'human rights', 'international'])
    },
    {
      id: 'thessaloniki', name: 'Thessaloniki International Film Festival', tier: 2,
      location: 'Thessaloniki, Greece', month: 'November',
      submission_opens: 'June 1',
      early_deadline: 'July 15', regular_deadline: 'August 15', late_deadline: 'September 1',
      fee_early: 0, fee_regular: 0, fee_late: 0,
      festival_start: '2027-11-04', festival_end: '2027-11-14',
      categories: JSON.stringify(['International Competition', 'Greek Cinema', 'Balkan Survey', 'Open Horizons', 'Shorts']),
      genres: JSON.stringify(['drama', 'documentary', 'experimental', 'comedy', 'animation']),
      prestige: 7, acceptance_rate: 0.025, runtime_min: 60, runtime_max: 200,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['Attenberg', 'Dogtooth', 'Miss Violence']),
      description: "Greece's most prestigious film festival. Strong Balkan and European cinema. Excellent for first and second features. Free to submit.",
      website: 'https://filmfestival.gr', platform: 'FilmFreeway',
      notes: 'Free to submit. Excellent launch point for European arthouse films. Balkan Survey section is perfect for regional films.',
      subject_tags: JSON.stringify(['Greek cinema', 'Balkan', 'European arthouse', 'first feature'])
    },
    {
      id: 'cleveland', name: 'Cleveland International Film Festival', tier: 2,
      location: 'Cleveland, Ohio, USA', month: 'April',
      submission_opens: 'September 1',
      early_deadline: 'October 15', regular_deadline: 'November 15', late_deadline: 'December 15',
      fee_early: 40, fee_regular: 50, fee_late: 65,
      festival_start: '2027-04-02', festival_end: '2027-04-13',
      categories: JSON.stringify(['International Feature', 'Documentary', 'Short Film', 'American Shorts', 'International Shorts']),
      genres: JSON.stringify(['drama', 'documentary', 'comedy', 'thriller', 'animation', 'short']),
      prestige: 6, acceptance_rate: 0.04, runtime_min: 0, runtime_max: 180,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['Still Alice', 'Boyhood', 'Beasts of the Southern Wild']),
      description: "One of the largest film festivals in the USA by attendance. Audience-focused with strong Midwest regional appeal.",
      website: 'https://clevelandfilm.org', platform: 'FilmFreeway',
      notes: 'Large, enthusiastic Midwest audience. Strong local press. Films with broad appeal often do very well here.',
      subject_tags: JSON.stringify(['Midwest', 'audience award', 'documentary', 'community'])
    },
    {
      id: 'nantucket', name: 'Nantucket Film Festival', tier: 2,
      location: 'Nantucket, Massachusetts, USA', month: 'June',
      submission_opens: 'November 1',
      early_deadline: 'January 15', regular_deadline: 'February 15', late_deadline: 'March 15',
      fee_early: 50, fee_regular: 65, fee_late: 85,
      festival_start: '2027-06-18', festival_end: '2027-06-22',
      categories: JSON.stringify(['Feature', 'Documentary', 'Short Film', 'Screenwriters Tribute']),
      genres: JSON.stringify(['drama', 'comedy', 'documentary', 'thriller']),
      prestige: 6, acceptance_rate: 0.04, runtime_min: 0, runtime_max: 180,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['Blue Jasmine', 'The Way, Way Back', 'The Perks of Being a Wallflower']),
      description: 'Intimate island festival celebrating screenwriting and storytelling. Strong industry attendance relative to its size. Known for its Screenwriters Tribute.',
      website: 'https://nantucketfilmfestival.org', platform: 'FilmFreeway',
      notes: 'Intimate atmosphere means excellent filmmaker-industry interaction. Strong focus on script quality and storytelling craft.',
      subject_tags: JSON.stringify(['screenplay', 'storytelling', 'intimate', 'New England'])
    },
    {
      id: 'santa-barbara', name: 'Santa Barbara International Film Festival', tier: 2,
      location: 'Santa Barbara, California, USA', month: 'February',
      submission_opens: 'August 1',
      early_deadline: 'September 15', regular_deadline: 'October 15', late_deadline: 'November 15',
      fee_early: 50, fee_regular: 65, fee_late: 80,
      festival_start: '2027-02-11', festival_end: '2027-02-21',
      categories: JSON.stringify(['New Visions', 'Documentary', 'International', 'Short Film', 'American Independents']),
      genres: JSON.stringify(['drama', 'documentary', 'comedy', 'thriller', 'animation', 'short']),
      prestige: 7, acceptance_rate: 0.03, runtime_min: 0, runtime_max: 180,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(["The Descendant's", 'Green Book', 'The Shape of Water', 'Birdman']),
      description: 'Award-season adjacent festival in the run-up to the Oscars. Hosts major award tributes. Strong industry presence.',
      website: 'https://sbiff.org', platform: 'FilmFreeway',
      notes: 'Oscar-adjacent programming with strong industry attendance. Award tributes bring major stars to town. Good for films in the awards conversation.',
      subject_tags: JSON.stringify(['Oscar season', 'awards', 'California', 'prestige'])
    },
    {
      id: 'mill-valley', name: 'Mill Valley Film Festival', tier: 2,
      location: 'Mill Valley, California, USA', month: 'October',
      submission_opens: 'May 1',
      early_deadline: 'June 15', regular_deadline: 'July 15', late_deadline: 'August 1',
      fee_early: 40, fee_regular: 55, fee_late: 70,
      festival_start: '2027-10-02', festival_end: '2027-10-12',
      categories: JSON.stringify(['World Cinema', 'Documentary', 'Short Film', 'Tribute']),
      genres: JSON.stringify(['drama', 'documentary', 'comedy', 'thriller', 'experimental', 'animation']),
      prestige: 7, acceptance_rate: 0.03, runtime_min: 0, runtime_max: 200,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['Lost in Translation', 'Sideways', 'Before Sunset']),
      description: 'Bay Area festival known for elegant programming and intimate atmosphere. Strong Bay Area film community and industry ties.',
      website: 'https://mvff.com', platform: 'FilmFreeway',
      notes: 'Great for Bay Area filmmakers and films with a West Coast sensibility. Intimate audience and strong press attendance.',
      subject_tags: JSON.stringify(['Bay Area', 'California', 'international', 'tribute'])
    },
    {
      id: 'hamptons', name: 'Hamptons International Film Festival', tier: 2,
      location: 'East Hampton, New York, USA', month: 'October',
      submission_opens: 'May 1',
      early_deadline: 'June 15', regular_deadline: 'July 15', late_deadline: 'August 15',
      fee_early: 50, fee_regular: 65, fee_late: 80,
      festival_start: '2027-10-08', festival_end: '2027-10-12',
      categories: JSON.stringify(['Golden Starfish Award', 'Documentary', 'Short Film', 'Spotlight']),
      genres: JSON.stringify(['drama', 'documentary', 'comedy', 'experimental', 'animation']),
      prestige: 7, acceptance_rate: 0.03, runtime_min: 0, runtime_max: 180,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['4 Months, 3 Weeks and 2 Days', 'The Artist', 'Beasts of the Southern Wild']),
      description: 'Upscale New York festival with strong access to East Coast media and entertainment industry. Awards season launching pad.',
      website: 'https://hamptonsfilmfest.org', platform: 'FilmFreeway',
      notes: 'Strong media and entertainment industry crowd. Films played here get good Oscar buzz. Upscale audience receptive to quality drama and documentary.',
      subject_tags: JSON.stringify(['New York', 'Oscar season', 'prestige', 'media'])
    },
    {
      id: 'raindance', name: 'Raindance Film Festival', tier: 2,
      location: 'London, UK', month: 'October',
      submission_opens: 'April 1',
      early_deadline: 'June 1', regular_deadline: 'July 15', late_deadline: 'August 15',
      fee_early: 25, fee_regular: 35, fee_late: 50,
      festival_start: '2027-10-22', festival_end: '2027-11-01',
      categories: JSON.stringify(['Feature', 'Documentary', 'Short Film', 'Web Series', 'VR']),
      genres: JSON.stringify(['drama', 'comedy', 'documentary', 'horror', 'thriller', 'experimental', 'sci-fi', 'animation']),
      prestige: 6, acceptance_rate: 0.06, runtime_min: 0, runtime_max: 180,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['The Blair Witch Project', 'Pulp Fiction', 'The Big Lebowski', "Lock, Stock and Two Smoking Barrels"]),
      description: "Europe's largest independent film festival. Focused on supporting truly independent cinema without studio backing.",
      website: 'https://raindance.org', platform: 'FilmFreeway',
      notes: 'Excellent for ultra-independent films. Very inclusive approach. BAFTA qualifying. Strong UK market for independent distribution.',
      subject_tags: JSON.stringify(['independent', 'ultra-low-budget', 'UK', 'BAFTA qualifier'])
    },
    {
      id: 'denver', name: 'Denver Film Festival', tier: 2,
      location: 'Denver, Colorado, USA', month: 'November',
      submission_opens: 'May 1',
      early_deadline: 'June 30', regular_deadline: 'August 1', late_deadline: 'September 1',
      fee_early: 40, fee_regular: 55, fee_late: 70,
      festival_start: '2027-11-06', festival_end: '2027-11-16',
      categories: JSON.stringify(['Feature Competition', 'Documentary Competition', 'Short Film', 'Animation']),
      genres: JSON.stringify(['drama', 'documentary', 'comedy', 'thriller', 'animation', 'short', 'experimental']),
      prestige: 6, acceptance_rate: 0.05, runtime_min: 0, runtime_max: 180,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['Nebraska', 'Her', 'Dallas Buyers Club']),
      description: 'Rocky Mountain region\'s most important festival. Large audience base and strong community engagement.',
      website: 'https://denverfilm.org', platform: 'FilmFreeway',
      notes: 'Strong Rocky Mountain regional audience. Good for films with outdoor/nature themes. Enthusiastic community.',
      subject_tags: JSON.stringify(['Rocky Mountain', 'Colorado', 'community', 'outdoor'])
    },
    {
      id: 'atlanta-ff', name: 'Atlanta Film Festival', tier: 2,
      location: 'Atlanta, Georgia, USA', month: 'March',
      submission_opens: 'September 1',
      early_deadline: 'October 15', regular_deadline: 'November 15', late_deadline: 'December 15',
      fee_early: 35, fee_regular: 50, fee_late: 65,
      festival_start: '2027-03-19', festival_end: '2027-03-30',
      categories: JSON.stringify(['Feature', 'Documentary', 'Short Film', 'Georgia Made']),
      genres: JSON.stringify(['drama', 'documentary', 'comedy', 'horror', 'thriller', 'short']),
      prestige: 6, acceptance_rate: 0.05, runtime_min: 0, runtime_max: 180,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['Mudbound', 'The Florida Project', 'BlacKkKlansman']),
      description: "The Southeast's most important film festival. Growing in prestige alongside Atlanta's film industry boom. Strong Southern storytelling focus.",
      website: 'https://atlantafilmfestival.com', platform: 'FilmFreeway',
      notes: "Growing festival in step with Atlanta's rise as a film production hub. Strong Southern US industry connections. Georgia Made section good for local productions.",
      subject_tags: JSON.stringify(['Southeast', 'Southern', 'Atlanta', 'Georgia', 'community'])
    },
    {
      id: 'cinequest', name: 'Cinequest Film & Creativity Festival', tier: 2,
      location: 'San Jose, California, USA', month: 'March',
      submission_opens: 'August 1',
      early_deadline: 'October 1', regular_deadline: 'November 1', late_deadline: 'December 1',
      fee_early: 35, fee_regular: 50, fee_late: 65,
      festival_start: '2027-03-04', festival_end: '2027-03-16',
      categories: JSON.stringify(['Feature', 'Documentary', 'Short Film', 'International', 'Maverick Spirit Award']),
      genres: JSON.stringify(['drama', 'comedy', 'documentary', 'sci-fi', 'thriller', 'experimental', 'animation']),
      prestige: 6, acceptance_rate: 0.05, runtime_min: 0, runtime_max: 200,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['Air Guitar Nation', 'Akeelah and the Bee', 'Run Lola Run']),
      description: 'Silicon Valley film festival at the intersection of film and technology. Maverick Spirit Award celebrates innovation in filmmaking.',
      website: 'https://cinequest.org', platform: 'FilmFreeway',
      notes: 'Great for tech-adjacent narratives and innovative filmmaking approaches. Silicon Valley audience is uniquely engaged. Maverick Spirit Award has real industry cachet.',
      subject_tags: JSON.stringify(['technology', 'innovation', 'Silicon Valley', 'maverick'])
    },
    {
      id: 'florida-ff', name: 'Florida Film Festival', tier: 2,
      location: 'Maitland, Florida, USA', month: 'April',
      submission_opens: 'September 1',
      early_deadline: 'November 1', regular_deadline: 'December 1', late_deadline: 'January 15',
      fee_early: 30, fee_regular: 45, fee_late: 60,
      festival_start: '2027-04-09', festival_end: '2027-04-18',
      categories: JSON.stringify(['Feature', 'Documentary', 'Short Film', 'Florida Spotlight']),
      genres: JSON.stringify(['drama', 'comedy', 'documentary', 'thriller', 'experimental', 'animation', 'short']),
      prestige: 6, acceptance_rate: 0.05, runtime_min: 0, runtime_max: 180,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify(['Hoop Dreams', 'Adaptation', 'Ed Wood']),
      description: 'Academy Award qualifying festival. One of the longest-running film festivals in Florida. Strong short film program.',
      website: 'https://floridafilmfestival.com', platform: 'FilmFreeway',
      notes: 'Oscar qualifying for short films and documentaries. Florida Spotlight section is great for films about the South or Florida specifically.',
      subject_tags: JSON.stringify(['Florida', 'Oscar qualifier', 'Southeast', 'short film'])
    },
    {
      id: 'fantastic-fest', name: 'Fantastic Fest', tier: 2,
      location: 'Austin, Texas, USA', month: 'September',
      submission_opens: 'March 1',
      early_deadline: 'May 1', regular_deadline: 'June 15', late_deadline: 'July 15',
      fee_early: 40, fee_regular: 55, fee_late: 70,
      festival_start: '2027-09-18', festival_end: '2027-09-25',
      categories: JSON.stringify(['Feature Competition', 'Short Film Competition', 'Midnights', 'Secret Screening']),
      genres: JSON.stringify(['horror', 'sci-fi', 'thriller', 'animation', 'experimental', 'comedy']),
      prestige: 7, acceptance_rate: 0.04, runtime_min: 0, runtime_max: 180,
      distribution_impact: 'high',
      notable_alumni: JSON.stringify(['The Babadook', 'Raw', 'Parasite (US premiere)', 'Get Out (early screening)', 'A Quiet Place']),
      description: "North America's largest genre film festival. The definitive platform for horror, sci-fi, and action films. Held at the famous Alamo Drafthouse.",
      website: 'https://fantasticfest.com', platform: 'FilmFreeway',
      notes: 'The best genre film festival in the US. Passionate, knowledgeable audience. Strong distribution interest from genre-specific buyers. Essential for horror and sci-fi.',
      subject_tags: JSON.stringify(['horror', 'genre', 'sci-fi', 'thriller', 'cult', 'Austin'])
    },

    // ── TIER 3 (additional) ───────────────────────────────────────────
    {
      id: 'sidewalk', name: 'Sidewalk Film Festival', tier: 3,
      location: 'Birmingham, Alabama, USA', month: 'August',
      submission_opens: 'January 1',
      early_deadline: 'March 1', regular_deadline: 'April 15', late_deadline: 'May 15',
      fee_early: 25, fee_regular: 35, fee_late: 50,
      festival_start: '2027-08-21', festival_end: '2027-08-24',
      categories: JSON.stringify(['Feature', 'Documentary', 'Short Film', 'Alabama Spotlight']),
      genres: JSON.stringify(['drama', 'comedy', 'documentary', 'horror', 'short']),
      prestige: 4, acceptance_rate: 0.10, runtime_min: 0, runtime_max: 180,
      distribution_impact: 'low',
      notable_alumni: JSON.stringify([]),
      description: "The Southeast's beloved community film festival. Strong local character and passionate audience. Alabama Spotlight section celebrates regional stories.",
      website: 'https://sidewalkfest.com', platform: 'FilmFreeway',
      notes: 'Great community atmosphere. Films about the South get warm receptions. Affordable submission fees.',
      subject_tags: JSON.stringify(['Southeast', 'Southern', 'community', 'Alabama', 'regional'])
    },
    {
      id: 'cucalorus', name: 'Cucalorus Film Festival', tier: 3,
      location: 'Wilmington, North Carolina, USA', month: 'November',
      submission_opens: 'April 1',
      early_deadline: 'June 15', regular_deadline: 'August 1', late_deadline: 'September 1',
      fee_early: 25, fee_regular: 35, fee_late: 50,
      festival_start: '2027-11-13', festival_end: '2027-11-17',
      categories: JSON.stringify(['Feature', 'Documentary', 'Short Film', 'Hatch Competition']),
      genres: JSON.stringify(['drama', 'comedy', 'documentary', 'experimental', 'short']),
      prestige: 4, acceptance_rate: 0.08, runtime_min: 0, runtime_max: 180,
      distribution_impact: 'low',
      notable_alumni: JSON.stringify([]),
      description: 'Quirky, community-driven festival in coastal North Carolina. Known for unusual programming and artist-friendly atmosphere. Hatch competition rewards innovation.',
      website: 'https://cucalorus.org', platform: 'FilmFreeway',
      notes: 'Welcoming to experimental and unusual work. Hatch competition supports emerging artists. Strong beach town atmosphere.',
      subject_tags: JSON.stringify(['North Carolina', 'experimental', 'community', 'Southern', 'indie'])
    },
    {
      id: 'oxford-ff', name: 'Oxford Film Festival', tier: 3,
      location: 'Oxford, Mississippi, USA', month: 'February',
      submission_opens: 'August 1',
      early_deadline: 'October 1', regular_deadline: 'November 1', late_deadline: 'December 1',
      fee_early: 20, fee_regular: 30, fee_late: 45,
      festival_start: '2027-02-19', festival_end: '2027-02-23',
      categories: JSON.stringify(['Feature', 'Documentary', 'Short Film', 'Made in Mississippi']),
      genres: JSON.stringify(['drama', 'comedy', 'documentary', 'short']),
      prestige: 3, acceptance_rate: 0.12, runtime_min: 0, runtime_max: 180,
      distribution_impact: 'low',
      notable_alumni: JSON.stringify([]),
      description: 'Small but beloved Southern film festival in the home of Faulkner. Intimate atmosphere and strong university community support.',
      website: 'https://oxfordfilmfest.com', platform: 'FilmFreeway',
      notes: 'Affordable fees and high acceptance rate. Great for Southern-themed films. Intimate festival where filmmakers get real face-time with audience.',
      subject_tags: JSON.stringify(['Southern', 'Mississippi', 'community', 'university', 'affordable'])
    },
    {
      id: 'bend', name: 'Bend Film Festival', tier: 3,
      location: 'Bend, Oregon, USA', month: 'October',
      submission_opens: 'March 1',
      early_deadline: 'May 1', regular_deadline: 'June 15', late_deadline: 'July 15',
      fee_early: 30, fee_regular: 45, fee_late: 60,
      festival_start: '2027-10-02', festival_end: '2027-10-05',
      categories: JSON.stringify(['Feature', 'Documentary', 'Short Film', 'Outdoor Film']),
      genres: JSON.stringify(['drama', 'documentary', 'experimental', 'short']),
      prestige: 4, acceptance_rate: 0.08, runtime_min: 0, runtime_max: 180,
      distribution_impact: 'low',
      notable_alumni: JSON.stringify([]),
      description: 'Pacific Northwest outdoor lifestyle festival. Strong focus on nature, adventure, and environmental themes. Outdoor screenings under the stars.',
      website: 'https://bendfilm.org', platform: 'FilmFreeway',
      notes: 'Perfect for outdoor adventure, environmental, and Pacific Northwest-themed films. Outdoor screening venue is magical.',
      subject_tags: JSON.stringify(['Pacific Northwest', 'outdoor', 'nature', 'environment', 'adventure'])
    },
    {
      id: 'wire-grass', name: 'Wiregrass Film Festival', tier: 3,
      location: 'Dothan, Alabama, USA', month: 'October',
      submission_opens: 'March 1',
      early_deadline: 'June 1', regular_deadline: 'July 15', late_deadline: 'August 15',
      fee_early: 15, fee_regular: 25, fee_late: 35,
      festival_start: '2027-10-09', festival_end: '2027-10-11',
      categories: JSON.stringify(['Feature', 'Short Film', 'Documentary', 'Southern Film']),
      genres: JSON.stringify(['drama', 'comedy', 'documentary', 'short']),
      prestige: 2, acceptance_rate: 0.20, runtime_min: 0, runtime_max: 180,
      distribution_impact: 'low',
      notable_alumni: JSON.stringify([]),
      description: 'Small, community-oriented festival in the heart of Alabama. Extremely affordable and accessible for emerging filmmakers.',
      website: 'https://wiregrassfilmfestival.com', platform: 'FilmFreeway',
      notes: 'Ultra-affordable fees. Great first festival experience. Supportive audience for emerging filmmakers.',
      subject_tags: JSON.stringify(['Southern', 'Alabama', 'affordable', 'emerging', 'community'])
    },
    {
      id: 'tribeca-shorts', name: 'Tribeca Shorts Competition', tier: 2,
      location: 'New York City, USA', month: 'June',
      submission_opens: 'October 1',
      early_deadline: 'November 15', regular_deadline: 'December 15', late_deadline: 'January 15',
      fee_early: 45, fee_regular: 60, fee_late: 80,
      festival_start: '2027-06-04', festival_end: '2027-06-15',
      categories: JSON.stringify(['Live Action Short', 'Documentary Short', 'Animated Short', 'Virtual Reality Short']),
      genres: JSON.stringify(['drama', 'documentary', 'animation', 'experimental', 'comedy', 'short']),
      prestige: 8, acceptance_rate: 0.005, runtime_min: 0, runtime_max: 40,
      distribution_impact: 'high',
      notable_alumni: JSON.stringify(['Two Distant Strangers (Oscar winner)', 'Hair Love (Oscar winner)', 'The Shore (Oscar winner)']),
      description: 'Oscar-qualifying short film competition at Tribeca. One of the most prestigious short film showcases in the US. Strong NYC media coverage.',
      website: 'https://tribecafilm.com', platform: 'FilmFreeway',
      notes: 'Oscar qualifying. NYC platform with strong press coverage. Best short film competition on the East Coast after Sundance.',
      subject_tags: JSON.stringify(['short film', 'Oscar qualifier', 'New York', 'animation', 'documentary short'])
    },
    {
      id: 'oscar-shorts', name: 'Oscar Qualifying Short Film Festivals Circuit', tier: 2,
      location: 'Various, USA/International', month: 'Various',
      submission_opens: 'January 1',
      early_deadline: 'March 1', regular_deadline: 'May 1', late_deadline: 'August 1',
      fee_early: 30, fee_regular: 45, fee_late: 60,
      festival_start: null, festival_end: null,
      categories: JSON.stringify(['Live Action Short', 'Documentary Short', 'Animated Short']),
      genres: JSON.stringify(['drama', 'documentary', 'animation', 'experimental', 'comedy', 'short']),
      prestige: 7, acceptance_rate: 0.03, runtime_min: 0, runtime_max: 40,
      distribution_impact: 'high',
      notable_alumni: JSON.stringify(['Two Distant Strangers', 'The Present', 'Feeling Through', 'Brotherhood']),
      description: 'Track of Oscar-qualifying film festivals specifically for short films. Qualifying at any one of these makes your film eligible for Oscar consideration.',
      website: 'https://oscars.org', platform: 'FilmFreeway',
      notes: 'Short films must qualify at an Academy-approved festival for Oscar eligibility. Pursue multiple qualifying festivals to increase chances of Oscar nomination.',
      subject_tags: JSON.stringify(['short film', 'Oscar qualifier', 'animation', 'documentary short', 'live action short'])
    },
    {
      id: 'cine-las-americas', name: 'Cine Las Américas International Film Festival', tier: 3,
      location: 'Austin, Texas, USA', month: 'April',
      submission_opens: 'October 1',
      early_deadline: 'December 1', regular_deadline: 'January 15', late_deadline: 'February 15',
      fee_early: 25, fee_regular: 35, fee_late: 50,
      festival_start: '2027-04-21', festival_end: '2027-04-27',
      categories: JSON.stringify(['Narrative Feature', 'Documentary Feature', 'Short Film', 'Animation']),
      genres: JSON.stringify(['drama', 'documentary', 'animation', 'comedy', 'experimental', 'short']),
      prestige: 5, acceptance_rate: 0.07, runtime_min: 0, runtime_max: 180,
      distribution_impact: 'medium',
      notable_alumni: JSON.stringify([]),
      description: 'Premier platform for Latin American, Latinx, and Indigenous cinema in the US. Strong connections to Spanish-language distribution.',
      website: 'https://cinelasamericas.org', platform: 'FilmFreeway',
      notes: 'Essential for Latin American and Latinx films seeking US distribution. Strong community in Austin. Good gateway to Spanish-language and US Latino audiences.',
      subject_tags: JSON.stringify(['Latin America', 'Latinx', 'Indigenous', 'Spanish language', 'Austin'])
    },
  ];

  db.exec('BEGIN');
  try {
    for (const f of festivals) {
      insert.run(f);
    }
    db.exec('COMMIT');
  } catch (e) {
    db.exec('ROLLBACK');
    throw e;
  }
}

module.exports = { seedFestivals };
